import tkinter as tk
from tkinter import ttk, messagebox
import random

from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg


# Colour palette
BG = "#F3F1EB"
CARD = "#FFFFFF"
TEXT = "#303030"
MUTED = "#777777"

GREEN = "#20A077"
GREEN_DARK = "#147A5C"
LIGHT_GREEN = "#E8F3DE"

LIGHT_RED = "#F9E8E8"
RED = "#9B3438"

LIGHT_YELLOW = "#FAF0DC"
ORANGE = "#D96A3B"

BORDER = "#D7D5CF"
GRAPH_GRID = "#E5E3DD"


# Temporary data for GUI testing.
#
# Expected file:
#     data_loader.py
#
# Expected function:
#     load_data()
#
# Expected return:
#     pandas DataFrame containing the well records and fields
#     required by the dashboard.

WELL_RISK = {
    "WELL-01": 82,
    "WELL-02": 14,
    "WELL-03": 58,
    "WELL-04": 9,
    "WELL-05": 21
}


RISK_HISTORY = {
    "WELL-01": [61, 58, 67, 74, 82],
    "WELL-02": [20, 18, 17, 15, 14],
    "WELL-03": [43, 47, 51, 55, 58],
    "WELL-04": [14, 12, 11, 10, 9],
    "WELL-05": [28, 25, 24, 23, 21]
}


# Temporary metric values for GUI testing.
#
# Expected fields from data_loader.py:
#     Oil_Rate
#     Gas_Rate
#     Pressure
#     Water_Cut
#     Choke_Position
#     Vibration
#     Motor_Current
#     Date

METRICS = {
    "oil": {
        "label": "Oil Rate",
        "title": "Oil Production",
        "unit": "bbl/day",
        "data": [100, 120, 115, 140, 135, 145, 132]
    },

    "gas": {
        "label": "Gas Rate",
        "title": "Gas Production",
        "unit": "MMscf/day",
        "data": [50, 65, 60, 75, 80, 78, 85]
    },

    "pressure": {
        "label": "Pressure",
        "title": "Well Pressure",
        "unit": "psi",
        "data": [70, 75, 72, 78, 80, 77, 82]
    },

    "water": {
        "label": "Water Cut",
        "title": "Water Cut",
        "unit": "%",
        "data": [20, 25, 23, 30, 28, 32, 29]
    },

    "choke": {
        "label": "Choke Position",
        "title": "Choke Position",
        "unit": "%",
        "data": [45, 50, 48, 55, 60, 58, 63]
    },

    "vibration": {
        "label": "Vibration",
        "title": "Equipment Vibration",
        "unit": "mm/s",
        "data": [2.1, 2.5, 2.3, 3.1, 3.5, 3.2, 3.8]
    },

    "motor_current": {
        "label": "Motor Current",
        "title": "Motor Current",
        "unit": "A",
        "data": [18, 21, 20, 24, 27, 26, 29]
    }
}


# Main window
window = tk.Tk()

window.title("Digital Oilfield Monitor")
window.geometry("1200x850")
window.minsize(1050, 750)
window.configure(bg=BG)


# Tkinter variables
well_var = tk.StringVar(value="WELL-01")
current_metric = tk.StringVar(value="oil")
current_period = tk.IntVar(value=7)
threshold_var = tk.DoubleVar(value=75)

risk_label = None
status_message = None
threshold_label = None
email_entry = None

well_labels = {}
metric_buttons = {}
period_buttons = {}


# Styles
style = ttk.Style()

try:
    style.theme_use("clam")
except tk.TclError:
    pass


style.configure(
    "Modern.TButton",
    font=("Segoe UI", 10, "bold"),
    padding=(14, 7),
    background=GREEN,
    foreground="white",
    borderwidth=0
)

style.map(
    "Modern.TButton",
    background=[
        ("active", GREEN_DARK),
        ("pressed", GREEN_DARK)
    ]
)


style.configure(
    "Modern.TCombobox",
    font=("Segoe UI", 10),
    padding=6
)


# Helper functions
def create_card(parent, **kwargs):
    """
    Creates a reusable dashboard card.

    The card provides a consistent background and border style
    for the different sections of the dashboard.
    """

    return tk.Frame(
        parent,
        bg=CARD,
        highlightbackground=BORDER,
        highlightthickness=1,
        **kwargs
    )


def create_section_title(parent, text, row=0, column=0):
    """
    Creates a consistent section heading for dashboard cards.
    """

    label = tk.Label(
        parent,
        text=text,
        font=("Segoe UI", 11, "bold"),
        bg=CARD,
        fg=TEXT
    )

    label.grid(
        row=row,
        column=column,
        sticky="w"
    )

    return label


def get_risk_status(risk):
    """
    Determines the risk classification and display colours.

    The selected threshold determines the boundary between
    HIGH RISK and WARNING.
    """

    threshold = threshold_var.get()

    if risk >= threshold:
        return "HIGH RISK", RED, LIGHT_RED

    if risk >= 50:
        return "WARNING", ORANGE, LIGHT_YELLOW

    return "NORMAL", GREEN, LIGHT_GREEN


# Well status
def update_well_status():
    """
    Updates the status cards for all wells.

    Integration:
        Replace the temporary WELL_RISK values with risk scores
        generated by the prediction module.
    """

    for well, label in well_labels.items():

        risk = WELL_RISK[well]

        status, colour, background = get_risk_status(risk)

        label.config(
            text=f"{well}\n{risk}%  {status}",
            fg=colour,
            bg=background
        )


def update_selected_well():
    """
    Updates the selected well without running diagnostics.

    Selecting a well only changes the selected-well context.
    A new risk assessment is generated only when the user clicks
    the Run Diagnostics button.
    """

    well = well_var.get()

    risk_label.config(
        text="--",
        fg=MUTED
    )

    status_message.config(
        text=f"{well} selected. Run diagnostics to assess current risk.",
        fg=MUTED
    )


def run_diagnostics():
    """
    Runs predictive maintenance diagnostics for the selected well.

    Integration:
        Replace the temporary WELL_RISK lookup with the prediction
        function supplied in predict.py.

    Expected function:
        predict_risk(well_data)
    """

    well = well_var.get()

    risk = WELL_RISK.get(
        well,
        0
    )

    status, colour, background = get_risk_status(risk)

    risk_label.config(
        text=f"{risk}%",
        fg=colour
    )

    status_message.config(
        text=f"Diagnostic result for {well}: {status}.",
        fg=colour
    )

    plot_risk_trend()


# Performance trend
def generate_period_data(metric, days):
    """
    Generates temporary metric data for the selected time period.

    This is used only for GUI testing.

    Integration:
        Replace this function with real historical data from
        data_loader.py when database integration is completed.
    """

    base_data = METRICS[metric]["data"]

    if days == 7:
        return base_data

    average = sum(base_data) / len(base_data)

    variation = max(
        average * 0.08,
        1
    )

    values = []

    for index in range(days):

        source_value = base_data[
            index % len(base_data)
        ]

        if index < len(base_data):

            value = source_value

        else:

            value = source_value + random.uniform(
                -variation,
                variation
            )

        values.append(
            round(value, 2)
        )

    return values


def select_period(days):
    """
    Changes the Performance Trend time period.

    Available periods:
        7 days
        15 days
        30 days
    """

    current_period.set(days)

    plot_chart(
        current_metric.get()
    )


def update_period_buttons():
    """
    Updates the appearance of the time-period buttons.
    """

    selected = current_period.get()

    for period, button in period_buttons.items():

        if period == selected:

            button.config(
                bg=GREEN,
                fg="white"
            )

        else:

            button.config(
                bg="#F5F4F0",
                fg=TEXT
            )


def plot_chart(metric):
    """
    Displays the selected production or equipment metric.

    The chart can display:
        - 7 days
        - 15 days
        - 30 days

    Integration:
        Replace the temporary generated values with historical
        values from the DataFrame returned by data_loader.py.

    The Date field from the DataFrame should be used for the
    x-axis after integration.
    """

    current_metric.set(metric)

    metric_info = METRICS[metric]

    days = current_period.get()

    values = generate_period_data(
        metric,
        days
    )

    title = metric_info["title"]
    unit = metric_info["unit"]

    ax.clear()

    x_values = list(
        range(days)
    )

    ax.plot(
        x_values,
        values,
        marker="o" if days <= 15 else None,
        linewidth=2.5,
        markersize=4,
        color=GREEN
    )

    ax.fill_between(
        x_values,
        values,
        alpha=0.08,
        color=GREEN
    )

    ax.set_title(
        f"{title} - Last {days} Days",
        fontsize=12,
        fontweight="bold",
        color=TEXT,
        pad=10
    )

    ax.set_ylabel(
        unit,
        fontsize=9,
        color=TEXT
    )

    if days == 7:

        tick_positions = list(
            range(7)
        )

        tick_labels = [
            "Day 1",
            "Day 2",
            "Day 3",
            "Day 4",
            "Day 5",
            "Day 6",
            "Day 7"
        ]

        ax.set_xticks(
            tick_positions
        )

        ax.set_xticklabels(
            tick_labels
        )

    elif days == 15:

        tick_positions = [
            0,
            2,
            4,
            6,
            8,
            10,
            12,
            14
        ]

        tick_labels = [
            "Day 1",
            "Day 3",
            "Day 5",
            "Day 7",
            "Day 9",
            "Day 11",
            "Day 13",
            "Day 15"
        ]

        ax.set_xticks(
            tick_positions
        )

        ax.set_xticklabels(
            tick_labels
        )

    else:

        tick_positions = [
            0,
            4,
            9,
            14,
            19,
            24,
            29
        ]

        tick_labels = [
            "Day 1",
            "Day 5",
            "Day 10",
            "Day 15",
            "Day 20",
            "Day 25",
            "Day 30"
        ]

        ax.set_xticks(
            tick_positions
        )

        ax.set_xticklabels(
            tick_labels
        )

    ax.tick_params(
        axis="both",
        labelsize=8,
        colors=MUTED
    )

    ax.grid(
        axis="y",
        linestyle="--",
        linewidth=0.7,
        color=GRAPH_GRID,
        alpha=0.9
    )

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    ax.spines["left"].set_color(BORDER)
    ax.spines["bottom"].set_color(BORDER)

    figure.tight_layout()

    canvas.draw()

    update_metric_buttons()
    update_period_buttons()


def update_metric_buttons():
    """
    Updates the appearance of the metric navigation buttons.
    """

    selected = current_metric.get()

    for metric, button in metric_buttons.items():

        if metric == selected:

            button.config(
                bg=GREEN,
                fg="white",
                relief="flat"
            )

        else:

            button.config(
                bg="#F5F4F0",
                fg=TEXT,
                relief="flat"
            )


# Risk trend chart
def plot_risk_trend():
    """
    Displays the recent diagnostic risk history for the selected well.

    Integration:
        Replace RISK_HISTORY with prediction results generated
        by predict.py.
    """

    well = well_var.get()

    values = RISK_HISTORY.get(
        well,
        [0, 0, 0, 0, 0]
    )

    risk_ax.clear()

    runs = [
        "Run 1",
        "Run 2",
        "Run 3",
        "Run 4",
        "Run 5"
    ]

    risk_ax.plot(
        runs,
        values,
        marker="o",
        linewidth=2.0,
        markersize=4,
        color=ORANGE
    )

    risk_ax.set_ylim(
        0,
        100
    )

    risk_ax.set_ylabel(
        "Risk %",
        fontsize=8,
        color=TEXT
    )

    risk_ax.tick_params(
        axis="both",
        labelsize=7,
        colors=MUTED
    )

    risk_ax.grid(
        axis="y",
        linestyle="--",
        linewidth=0.6,
        color=GRAPH_GRID
    )

    risk_ax.spines["top"].set_visible(False)
    risk_ax.spines["right"].set_visible(False)

    risk_ax.spines["left"].set_color(BORDER)
    risk_ax.spines["bottom"].set_color(BORDER)

    risk_figure.tight_layout()

    risk_canvas.draw()


# Alert threshold
def update_threshold(value):
    """
    Updates the risk threshold displayed by the dashboard.

    Changing the threshold does not run a new diagnostic.
    """

    threshold = float(value)

    threshold_label.config(
        text=f"{threshold:.0f}%"
    )

    update_well_status()


# Reports and email
def technical_report():
    """
    Generates the Technical Report for the selected well.

    Project requirement:
        - Mean values
        - Maximum values
        - Standard deviation

    Integration:
        Connect this function to reports.py.
    """

    messagebox.showinfo(
        "Technical Report",
        "Technical report generation will be connected to the reporting module."
    )


def stakeholder_report():
    """
    Generates the Stakeholder Report.

    Project requirement:
        - Total oil produced
        - Field status

    Integration:
        Connect this function to reports.py.
    """

    messagebox.showinfo(
        "Stakeholder Report",
        "Stakeholder report generation will be connected to the reporting module."
    )


def send_report():
    """
    Sends the generated report to the recipient entered by the user.

    Integration:
        Connect this function to the SMTP function from emailer.py.
    """

    email = email_entry.get().strip()

    if not email or email == "name@company.com":

        messagebox.showwarning(
            "Email Required",
            "Please enter an email address."
        )

        return

    if "@" not in email or "." not in email:

        messagebox.showwarning(
            "Invalid Email",
            "Please enter a valid email address."
        )

        return

    messagebox.showinfo(
        "Report Sent",
        f"Report prepared for:\n{email}\n\n"
        "SMTP integration can be connected here."
    )


# Main dashboard container
main = tk.Frame(
    window,
    bg=BG
)

main.pack(
    fill="both",
    expand=True,
    padx=18,
    pady=12
)


# Configure main responsive grid
main.columnconfigure(
    0,
    weight=3
)

main.columnconfigure(
    1,
    weight=2
)

main.rowconfigure(
    2,
    weight=4
)


# Header
header = create_card(main)

header.grid(
    row=0,
    column=0,
    columnspan=2,
    sticky="ew",
    pady=(0, 8)
)


header_content = tk.Frame(
    header,
    bg=CARD
)

header_content.grid(
    row=0,
    column=0,
    sticky="ew",
    padx=18,
    pady=10
)

header_content.columnconfigure(
    0,
    weight=1
)


tk.Label(
    header_content,
    text="Digital Oilfield Monitor",
    font=("Segoe UI", 19, "bold"),
    bg=CARD,
    fg=TEXT
).grid(
    row=0,
    column=0,
    sticky="w"
)


tk.Label(
    header_content,
    text="Real-time production, equipment and risk monitoring",
    font=("Segoe UI", 9),
    bg=CARD,
    fg=MUTED
).grid(
    row=1,
    column=0,
    sticky="w",
    pady=(2, 0)
)


live_frame = tk.Frame(
    header_content,
    bg=CARD
)

live_frame.grid(
    row=0,
    column=1,
    rowspan=2,
    sticky="e"
)


tk.Label(
    live_frame,
    text="●",
    font=("Segoe UI", 12),
    bg=CARD,
    fg=GREEN
).grid(
    row=0,
    column=0,
    padx=(0, 5)
)


tk.Label(
    live_frame,
    text="LIVE MONITORING",
    font=("Segoe UI", 8, "bold"),
    bg=CARD,
    fg=GREEN_DARK
).grid(
    row=0,
    column=1
)


# Well status card
well_card = create_card(main)

well_card.grid(
    row=1,
    column=0,
    columnspan=2,
    sticky="ew",
    pady=(0, 8)
)


well_content = tk.Frame(
    well_card,
    bg=CARD
)

well_content.grid(
    row=0,
    column=0,
    sticky="ew",
    padx=14,
    pady=8
)

well_content.columnconfigure(
    0,
    weight=1
)


create_section_title(
    well_content,
    "Well Status"
)


status_grid = tk.Frame(
    well_content,
    bg=CARD
)

status_grid.grid(
    row=1,
    column=0,
    sticky="ew",
    pady=(7, 7)
)


for index, well in enumerate(WELL_RISK):

    status_grid.columnconfigure(
        index,
        weight=1
    )

    status_label = tk.Label(
        status_grid,
        text="",
        font=("Segoe UI", 8, "bold"),
        height=2,
        relief="flat",
        bd=0
    )

    status_label.grid(
        row=0,
        column=index,
        padx=3,
        sticky="ew"
    )

    well_labels[well] = status_label


# Well controls
control_frame = tk.Frame(
    well_content,
    bg=CARD
)

control_frame.grid(
    row=2,
    column=0,
    sticky="ew"
)


tk.Label(
    control_frame,
    text="Select Well",
    font=("Segoe UI", 9, "bold"),
    bg=CARD,
    fg=TEXT
).grid(
    row=0,
    column=0,
    padx=(0, 7),
    sticky="w"
)


well_selector = ttk.Combobox(
    control_frame,
    textvariable=well_var,
    values=list(WELL_RISK.keys()),
    state="readonly",
    width=14,
    style="Modern.TCombobox"
)

well_selector.grid(
    row=0,
    column=1,
    sticky="w"
)

well_selector.bind(
    "<<ComboboxSelected>>",
    lambda event: update_selected_well()
)


ttk.Button(
    control_frame,
    text="Run Diagnostics",
    command=run_diagnostics,
    style="Modern.TButton"
).grid(
    row=0,
    column=2,
    padx=(10, 0),
    sticky="w"
)


# Performance trend card
chart_card = create_card(main)

chart_card.grid(
    row=2,
    column=0,
    sticky="nsew",
    padx=(0, 5),
    pady=(0, 8)
)

chart_card.columnconfigure(
    0,
    weight=1
)

chart_card.rowconfigure(
    2,
    weight=1
)


# Performance trend header
chart_header = tk.Frame(
    chart_card,
    bg=CARD
)

chart_header.grid(
    row=0,
    column=0,
    sticky="ew",
    padx=14,
    pady=(9, 0)
)

chart_header.columnconfigure(
    0,
    weight=1
)


create_section_title(
    chart_header,
    "Performance Trend"
)


tk.Label(
    chart_header,
    text="Production and equipment operating trend",
    font=("Segoe UI", 8),
    bg=CARD,
    fg=MUTED
).grid(
    row=1,
    column=0,
    sticky="w",
    pady=(1, 0)
)


# Time period buttons
period_frame = tk.Frame(
    chart_header,
    bg=CARD
)

period_frame.grid(
    row=0,
    column=1,
    rowspan=2,
    sticky="e"
)


periods = [
    (7, "7 Days"),
    (15, "15 Days"),
    (30, "30 Days")
]


for index, (days, label) in enumerate(periods):

    button = tk.Button(
        period_frame,
        text=label,
        font=("Segoe UI", 8, "bold"),
        bg="#F5F4F0",
        fg=TEXT,
        bd=0,
        relief="flat",
        cursor="hand2",
        padx=10,
        pady=5,
        command=lambda value=days: select_period(value)
    )

    button.grid(
        row=0,
        column=index,
        padx=2
    )

    period_buttons[days] = button


# Performance chart
chart_area = tk.Frame(
    chart_card,
    bg=CARD
)

chart_area.grid(
    row=2,
    column=0,
    sticky="nsew",
    padx=10,
    pady=4
)


figure = Figure(
    figsize=(7, 3),
    dpi=100,
    facecolor=CARD
)

ax = figure.add_subplot(111)

ax.set_facecolor(CARD)


canvas = FigureCanvasTkAgg(
    figure,
    master=chart_area
)

canvas.get_tk_widget().pack(
    fill="both",
    expand=True
)


# Risk assessment card
risk_card = create_card(main)

risk_card.grid(
    row=2,
    column=1,
    sticky="nsew",
    padx=(5, 0),
    pady=(0, 8)
)

risk_card.columnconfigure(
    0,
    weight=1
)

risk_card.rowconfigure(
    2,
    weight=1
)


risk_content = tk.Frame(
    risk_card,
    bg=CARD
)

risk_content.grid(
    row=0,
    column=0,
    sticky="nsew",
    padx=14,
    pady=9
)

risk_content.columnconfigure(
    0,
    weight=1
)

risk_content.rowconfigure(
    2,
    weight=1
)


create_section_title(
    risk_content,
    "Risk Assessment"
)


risk_summary = tk.Frame(
    risk_content,
    bg=CARD
)

risk_summary.grid(
    row=1,
    column=0,
    sticky="ew",
    pady=(7, 2)
)


risk_label = tk.Label(
    risk_summary,
    text="--",
    font=("Segoe UI", 22, "bold"),
    bg=CARD,
    fg=MUTED
)

risk_label.grid(
    row=0,
    column=0,
    sticky="w"
)


status_message = tk.Label(
    risk_summary,
    text="WELL-01 selected. Run diagnostics to assess current risk.",
    font=("Segoe UI", 8, "bold"),
    bg=CARD,
    fg=MUTED,
    wraplength=300,
    justify="left"
)

status_message.grid(
    row=1,
    column=0,
    sticky="w",
    pady=(2, 0)
)


risk_figure = Figure(
    figsize=(4, 1.5),
    dpi=100,
    facecolor=CARD
)

risk_ax = risk_figure.add_subplot(111)

risk_ax.set_facecolor(CARD)


risk_canvas = FigureCanvasTkAgg(
    risk_figure,
    master=risk_content
)

risk_canvas.get_tk_widget().grid(
    row=2,
    column=0,
    sticky="nsew",
    pady=(2, 0)
)


# Alert threshold card
threshold_card = create_card(main)

threshold_card.grid(
    row=3,
    column=0,
    columnspan=2,
    sticky="ew",
    pady=(0, 8)
)


threshold_content = tk.Frame(
    threshold_card,
    bg=CARD
)

threshold_content.grid(
    row=0,
    column=0,
    sticky="ew",
    padx=14,
    pady=9
)

threshold_content.columnconfigure(
    1,
    weight=1
)


create_section_title(
    threshold_content,
    "Alert Threshold"
)


tk.Label(
    threshold_content,
    text="Set the risk percentage at which a well becomes high risk.",
    font=("Segoe UI", 8),
    bg=CARD,
    fg=MUTED
).grid(
    row=1,
    column=0,
    sticky="w",
    pady=(2, 0)
)


threshold_scale = tk.Scale(
    threshold_content,
    from_=0,
    to=100,
    orient="horizontal",
    variable=threshold_var,
    command=update_threshold,
    showvalue=False,
    resolution=1,
    bg=CARD,
    fg=TEXT,
    troughcolor="#E6E4DE",
    activebackground=GREEN,
    highlightthickness=0,
    bd=0
)

threshold_scale.grid(
    row=0,
    column=1,
    rowspan=2,
    sticky="ew",
    padx=(25, 10)
)


threshold_label = tk.Label(
    threshold_content,
    text="75%",
    font=("Segoe UI", 13, "bold"),
    bg=CARD,
    fg=GREEN_DARK,
    width=5
)

threshold_label.grid(
    row=0,
    column=2,
    rowspan=2,
    sticky="e"
)


# Metric navigation
metric_card = create_card(main)

metric_card.grid(
    row=4,
    column=0,
    columnspan=2,
    sticky="ew",
    pady=(0, 8)
)


metric_content = tk.Frame(
    metric_card,
    bg=CARD
)

metric_content.grid(
    row=0,
    column=0,
    sticky="ew",
    padx=7,
    pady=6
)


for index in range(7):

    metric_content.columnconfigure(
        index,
        weight=1
    )


metric_names = [
    ("oil", "Oil Rate"),
    ("gas", "Gas Rate"),
    ("pressure", "Pressure"),
    ("water", "Water Cut"),
    ("choke", "Choke Position"),
    ("vibration", "Vibration"),
    ("motor_current", "Motor Current")
]


for index, (metric, label) in enumerate(metric_names):

    button = tk.Button(
        metric_content,
        text=label,
        font=("Segoe UI", 8, "bold"),
        bg="#F5F4F0",
        fg=TEXT,
        bd=0,
        relief="flat",
        cursor="hand2",
        padx=4,
        pady=6,
        command=lambda m=metric: plot_chart(m)
    )

    button.grid(
        row=0,
        column=index,
        padx=2,
        sticky="ew"
    )

    metric_buttons[metric] = button


# Reports and notifications
report_card = create_card(main)

report_card.grid(
    row=5,
    column=0,
    columnspan=2,
    sticky="ew"
)


report_content = tk.Frame(
    report_card,
    bg=CARD
)

report_content.grid(
    row=0,
    column=0,
    sticky="ew",
    padx=14,
    pady=8
)

report_content.columnconfigure(
    3,
    weight=1
)


create_section_title(
    report_content,
    "Reports & Notifications"
)


tk.Label(
    report_content,
    text="Generate reports or send results to stakeholders.",
    font=("Segoe UI", 8),
    bg=CARD,
    fg=MUTED
).grid(
    row=1,
    column=0,
    sticky="w"
)


ttk.Button(
    report_content,
    text="Technical Report",
    command=technical_report,
    style="Modern.TButton"
).grid(
    row=0,
    column=1,
    rowspan=2,
    padx=(20, 6)
)


ttk.Button(
    report_content,
    text="Stakeholder Report",
    command=stakeholder_report,
    style="Modern.TButton"
).grid(
    row=0,
    column=2,
    rowspan=2,
    padx=(0, 12)
)


# Email entry
email_entry = tk.Entry(
    report_content,
    font=("Segoe UI", 9),
    relief="solid",
    bd=1
)

email_entry.grid(
    row=0,
    column=3,
    rowspan=2,
    sticky="ew",
    ipady=5,
    padx=(0, 7)
)

email_entry.insert(
    0,
    "name@company.com"
)

email_entry.config(
    fg=MUTED
)


def clear_email_placeholder(event):
    """
    Removes the email placeholder when the entry field receives focus.
    """

    if email_entry.get() == "name@company.com":

        email_entry.delete(
            0,
            tk.END
        )

        email_entry.config(
            fg=TEXT
        )


def restore_email_placeholder(event):
    """
    Restores the email placeholder when no address has been entered.
    """

    if not email_entry.get().strip():

        email_entry.insert(
            0,
            "name@company.com"
        )

        email_entry.config(
            fg=MUTED
        )


email_entry.bind(
    "<FocusIn>",
    clear_email_placeholder
)

email_entry.bind(
    "<FocusOut>",
    restore_email_placeholder
)


ttk.Button(
    report_content,
    text="Send Report",
    command=send_report,
    style="Modern.TButton"
).grid(
    row=0,
    column=4,
    rowspan=2
)


# Initial display
update_well_status()

risk_label.config(
    text="--",
    fg=MUTED
)

status_message.config(
    text=f"{well_var.get()} selected. Run diagnostics to assess current risk.",
    fg=MUTED
)

plot_chart("oil")
update_metric_buttons()
update_period_buttons()


window.mainloop()